version: "3.9"

services:
  app:
    container_name: app
    build: .
    ports:
      - 8080:8080
    restart: always
    environment:
      POSTGRES_SERVER: localhost
      POSTGRES_PORT: 8080
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    links:
      - db:db_domain
    depends_on:
      - db

  db:
    container_name: yandex-lavka-db
    image: postgres:14.7 #15.2
#    volumes:
#      - dbvolume:/var/lib/postgresql/dbvolume
    ports:
      - "5431:5431"
    environment:
      POSTGRES_DB: lavka
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  dbvolume:
